name = "CCCE Modded"
author = "verdantfuture"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b9550a3f9ae81f9db2f28dc8239062ab05b10f830bf0b1a4b4fb30e7a34347a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.93"
