name = "CCCE Modded"
author = "verdantfuture"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b85cfa68f299e2d52fda8da8bba241ca697bff2fddf6419123f60641cf30c63"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.93"
