name = "CCCE Modded"
author = "verdantfuture"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f40d2a1bdf3d3320e0bd741387e8b60069db54b4a4f7c58c3ce1e1bcfb082d13"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.93"
