name = "CCCE Modded"
author = "verdantfuture"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9dc195f992e380d5230e0845c2d2051feaa3300a291726130c107d5611b530b0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.93"
